# Generated by Django 3.0.2 on 2020-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='user_id',
            new_name='user',
        ),
    ]
